views/domain_manger.py
#!/usr/bin/env python3
# -*- coding=UTF-8 -*-
'''
@Description: 站点管理相关代码
@Author: bayonet
@Github: https://github.com/hyll8882019
@Date: 2019-07-30 19:43:59
@LastEditors: bayonet
@LastEditTime: 2019-07-30 20:24:25
'''
from datetime import datetime, timedelta

from flask import Blueprint, jsonify, render_template, request

from config import *
from public.helper import *
from views.login import login_check

domain = Blueprint('domain', __name__)


@domain.route('/show_domain_list', methods=['GET', ])
@login_check
def show_domain_list():
    current_page = int(request.args.get('page', '1'))

    conn = get_connect()
    db_domain = conn.domain_manager.db_domain
    max_show_num = current_page * MAX_SHOW_NUMBER
    min_show_num = max_show_num - MAX_SHOW_NUMBER
    data = db_domain.find().skip(min_show_num).limit(MAX_SHOW_NUMBER)
    t = db_domain.count_documents({})
    page, max_page = page_format(current_page, t, MAX_SHOW_NUMBER)
    conn.close()
    return render_template('show_domain_list.html', data=data, page=page, current_page=current_page, max_page=max_page)


@domain.route('/api/add_domain', methods=['POST', ])
@login_check
def add_domain():
    info = {'status': False, 'info': '插入数据库失败'}
    if request.method == 'POST':
        title = request.form['title']  # 网站名称
        url = request.form['url']  # 网站地址
        rank_name = request.form['rankname']  # 备注
        js_jump = request.form['js_jump']  # JS 地址
        tpl_name = request.form['tpl_name']  # 模板名
        dir_prefix = request.form['dir_prefix']  # 目录前缀
        web_server_classe = request.form['webserver_classe']  # Web容器
        error_page = request.form['error_page']  # 404错误页
        no_access = request.form['no_access']  # 地区屏蔽
        spider_rules = request.form['spider_rules'].split()  # 放行蜘蛛
        add_time = datetime.today().strftime('%Y-%m-%d %H:%M:%S')  # 添加日期
        conn = get_connect()
        db_domain = conn.domain_manager.db_domain

        # 自动添加到链轮库
        rules = ['/hot<随机字符>/', '/hot<随机字符>.html',
                 '/app<随机字符>/', '/app<随机字符>.html']  # 默认路由规则
        hit = 2
        add_time = datetime.today().strftime('%Y-%m-%d %H:%M:%S')  # 添加日期
        pool_link = conn.domain_manager.pool_link

        if pool_link.find_one({'_id': url}) is None:
            result = pool_link.insert_one(
                {'_id': url, 'rules': rules, 'hit': hit, 'add_time': add_time})

        if db_domain.find_one({'_id': url}) is None:
            result = db_domain.insert_one(
                {'_id': url, 'title': title, 'rankname': rank_name, 'js_jump': js_jump, 'tpl_name': tpl_name,
                 'dir_prefix': dir_prefix, 'webserver_classe': web_server_classe, 'error_page': error_page,
                 'no_access': no_access, 'add_time': add_time, 'baidu_token': '', 'spider_rules': spider_rules})
            info['status'] = True
            info['info'] = '添加成功'
        else:
            info['status'] = False
            info['info'] = '域名已经存在'
        conn.close()
    return jsonify(info)


@domain.route('/api/edit_domain', methods=['POST', ])
@login_check
def edit_domain():
    info = {'status': False, 'info': ''}
    if request.method == 'POST':
        conn = get_connect()
        db_domain = conn.domain_manager.db_domain
        domain = db_domain.find_one({'_id': request.form['sid']})

        if domain is None:
            info['info'] = '站点不存在'
            return jsonify(info)

        domain['js_jump'] = request.form['js_jump']
        domain['rankname'] = request.form['rankname']
        domain['dir_prefix'] = request.form['dir_prefix']
        domain['tpl_name'] = request.form['tpl_name']
        domain['no_access'] = request.form['no_access']
        domain['error_page'] = request.form['error_page']
        domain['webserver_classe'] = request.form['webserver_classe']
        domain['baidu_token'] = request.form['baidu_token']
        domain['spider_rules'] = request.form['spider_rules'].split()  # 放行蜘蛛
        db_domain.update({'_id': request.form['sid']}, domain)
        info['info'] = '修改成功'
        info['status'] = True
        return jsonify(info)

    info['info'] = '异常请求'
    return jsonify(info)


@domain.route('/api/del_domian', methods=['POST', ])
@login_check
def del_domain():
    info = {'status': False, 'info': ''}
    if request.method == 'POST':
        conn = get_connect()
        db_domain = conn.domain_manager.db_domain
        db_domain.delete_one({'_id': request.form['sid']})
        info['info'] = '删除成功'
        info['status'] = True
        return jsonify(info)

    info['info'] = '异常请求'
    return jsonify(info)


@domain.route('/api/find_domain', methods=['POST', ])
@login_check
def find_domain():
    info = {'status': False, 'info': '站点不存在', 'data': None}
    if request.method == 'POST':
        try:
            sid = request.form['sid']
        except KeyError:
            return jsonify(info)
        conn = get_connect()
        db_domain = conn.domain_manager.db_domain
        info['data'] = db_domain.find_one({'_id': sid})
        info['status'] = True
        info['info'] = ''
        conn.close()
        return jsonify(info)
    info['info'] = '异常请求'
    return jsonify(info)

views/login.py
#!/usr/bin/env python3
# -*- coding=UTF-8 -*-
'''
@Description: 自定义登录函数
@Author: bayonet
@Github: https://github.com/hyll8882019
@Date: 2019-07-30 19:48:59
@LastEditors: bayonet
@LastEditTime: 2019-07-30 20:17:55
'''

from flask import request
from config import PASSWORD

def login_check(func):
    '''
    @description: 登录验证. 只验证Cookies
    '''
    def wrapper(*args, **kwargs):
        ss = request.cookies.get("ss", None)
        if ss is None or ss != PASSWORD:
            return "404"
        return func(*args, **kwargs)

    wrapper.__name__ = func.__name__
    return wrapper

views/pool_link.py
#!/usr/bin/env python3
# -*- coding=UTF-8 -*-
'''
@Description: 轮链管理相关代码
@Author: bayonet
@Github: https://github.com/hyll8882019
@Date: 2019-07-30 19:44:29
@LastEditors: bayonet
@LastEditTime: 2019-07-30 20:24:15
'''
from datetime import datetime, timedelta

from flask import Blueprint, jsonify, render_template, request

from config import *
from public.helper import *
from views.login import login_check
link = Blueprint('link', __name__)


@link.route('/api/show_pool_link')
@login_check
def show_pool_link():
    current_page = int(request.args.get('page', '1'))

    conn = get_connect()
    pool_link = conn.domain_manager.pool_link
    max_show_num = current_page * MAX_SHOW_NUMBER
    min_show_num = max_show_num - MAX_SHOW_NUMBER
    data = pool_link.find().skip(min_show_num).limit(MAX_SHOW_NUMBER)
    t = pool_link.count_documents({})
    page, max_page = page_format(current_page, t, 20)
    return render_template('show_pool_link.html', data=data, page=page, current_page=current_page, max_page=max_page)


@link.route('/api/add_pool_link', methods=['POST', ])
@login_check
def add_pool_link():
    info = {'status': False, 'info': '插入数据库失败'}
    if request.method == 'POST':
        domain = request.form['slink_domain']  # 网站地址
        rules = request.form['slink_rules'].split()  # 路由规则
        hit = request.form['slink_level']  # 权重
        add_time = datetime.today().strftime('%Y-%m-%d %H:%M:%S')  # 添加日期

        conn = get_connect()
        db_domain = conn.domain_manager.pool_link
        if db_domain.find_one({'_id': domain}) is None:
            result = db_domain.insert_one(
                {'_id': domain, 'rules': rules, 'hit': hit, 'add_time': add_time})
            info['status'] = True
            info['info'] = '添加成功'
        else:
            info['status'] = False
            info['info'] = '域名已经存在'
        conn.close()
    return jsonify(info)


@link.route('/api/find_pool_link', methods=['POST', ])
@login_check
def find_pool_link():
    info = {'status': False, 'info': '轮链不存在', 'data': None}
    if request.method == 'POST':
        try:
            sid = request.form['sid']
        except KeyError:
            return jsonify(info)
        conn = get_connect()
        db_domain = conn.domain_manager.pool_link
        info['data'] = db_domain.find_one({'_id': sid})
        info['status'] = True
        info['info'] = ''
        conn.close()
        return jsonify(info)

    info['info'] = '异常请求'
    return jsonify(info)


@link.route('/api/edit_pool_link', methods=['POST', ])
@login_check
def edit_pool_link():
    info = {'status': False, 'info': ''}
    if request.method == 'POST':
        conn = get_connect()
        db_domain = conn.domain_manager.pool_link
        domain = db_domain.find_one({'_id': request.form['sid']})

        if domain is None:
            info['info'] = '站点不存在'
            return jsonify(info)

        domain['hit'] = request.form['slink_level']
        domain['rules'] = request.form['slink_rules'].split()

        db_domain.update({'_id': request.form['sid']}, domain)
        info['info'] = '修改成功'
        info['status'] = True
        return jsonify(info)

    info['info'] = '异常请求'
    return jsonify(info)


@link.route('/api/del_pool_link', methods=['POST', ])
@login_check
def del_pool_link():
    info = {'status': False, 'info': ''}
    if request.method == 'POST':
        conn = get_connect()
        db_domain = conn.domain_manager.pool_link
        db_domain.delete_one({'_id': request.form['sid']})
        info['info'] = '删除成功'
        info['status'] = True
        return jsonify(info)

    info['info'] = '异常请求'
    return jsonify(info)

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block base_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/ace.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-multiselect.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% endblock %}
    {% block load_css %}
    {% endblock %}
    <title>{% block title %} {% endblock %}-SEO管理系统</title>
</head>
<body>
{% with messages = get_flashed_messages() %}
{% if messages %}
    <ul class="flash">
        {% for message in messages %}
            <div class="alert alert-success" style="text-align: center">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <strong>{{ message }}</strong></div>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %}
    
{% block body %}
{% endblock %}

{% block base_js %}
<script src="{{ url_for('static', filename='js/jquery-1.10.2.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/typeahead-bs2.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery-ui-1.10.3.custom.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.ui.touch-punch.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.easy-pie-chart.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.sparkline.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.flot.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.flot.pie.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.flot.resize.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/ace-elements.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/ace.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/base.js') }}"></script>
{% endblock %}

{% block load_js %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends "nav.html" %}

{% block content %}
<div class="page-header">
    <h1>
        <i class="fa fa-home"></i> 首页
    </h1>
</div>
<div class="col-xs-12">
    <div class="tabbable">后台首页</div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}SEO管理后台登录{% endblock %}

{% block load_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}

{% block body %}

<div class="container">
    <form action="{{ url_for('login') }}" class="form-signin" method="POST">
        <h2 class="form-signin-heading">SEO管理后台登录</h2>
        <label for="inputUsername" class="sr-only">账号</label>
        <input type="text" name="username" class="form-control" placeholder="用户名" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" name="password" class="form-control" placeholder="密码" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
    </form>
</div>

{% endblock %}


templates/show_pool_link.html
{% extends "nav.html" %}
{% block title %}轮链管理{% endblock %}
{% block content %}
    <div class="page-header"><h1> 链接池管理 &gt; 目录反代管理</h1></div>
    <div class="col-xs-12">
        <div class="tabbable">
            <ul class="nav nav-tabs padding-12 tab-color-blue background-blue"
                id="myTab">
                <li class="active"><a href="#home" data-toggle="tab">链接池列表</a></li>
                <li><a href="javascript:;" onclick="add()">添加链接</a></li>
            </ul>
        </div>
        <div class="tabbable">
            <div class="tab-content">
                <table class="table table-bordered table-hover">
                    <tr>
                        <!-- <th>链接ID</th> -->
                        <th>链接域名</th>
                        <th>链接规则</th>
                        <th>链接等级</th>
                        <th>添加时间</th>
                        <th>操作</th>
                    </tr>
                    {% for i in data %}
                        <tr>
                            <td><a href="javascript:;" name="domain">{{ i._id }}</a></td>
                            <td>
                                <details>
                                    <summary>该域名有<b>{{ i.rules | length }}</b>个链接规则</summary>
                                    <ul>
                                        {% for link in i.rules %}
                                            <li> {{ link }}</li>
                                        {% endfor %}
                                    </ul>
                                </details>
                            </td>
                            <td>
                                {% if i.hit == '2' %}<code>高</code>{% endif %}
                                {% if i.hit == '1' %}<code>中</code>{% endif %}
                                {% if i.hit == '0' %}<code>低</code>{% endif %}
                            </td>
                            <td>{{ i.add_time }}</td>
                            <td>
                                <a class="btn-xs btn-primary" data-site-sid="{{ i._id }}" name="ViewSite"
                                   href="javascript:void(0);">View</a>&nbsp;
                                <a class="btn-xs btn-danger" name="DeleteSite" data-site-sid="{{ i._id }}"
                                   href="javascript:void(0);">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <nav style="text-align: center">
                    <ul class="pagination">
                        <li><a class="start" href="{{ url_for('link.show_pool_link', page='1') }}">首页</a></li>
                        {% for p in page %}
                            {% if current_page == p %}
                                <li class="active"><a class="num"
                                                      href="{{ url_for('link.show_pool_link', page=current_page) }}">{{ p }}</a>
                                </li>
                            {% else %}
                                <li><a class="num" href="{{ url_for('link.show_pool_link', page=p) }}">{{ p }}</a></li>
                            {% endif %}
                        {% endfor %}
                        <li><a class="end" href="{{ url_for('link.show_pool_link', page=max_page) }}">尾页</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- 添加站点开始 -->
    <div class="modal fade" id="bjy-add" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true"> &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel"> 添加链接</h4>
                </div>
                <div class="modal-body">
                    <form id="bjy-form" class="form-inline" action="{{ url_for('link.add_pool_link') }}" method="post">
                        <table class="table table-striped table-bordered table-hover table-condensed">
                            <tr>
                                <th width="15%">链接地址:</th>
                                <td>
                                    <input class="input-medium" type="text" name="slink_domain" style="width: 100%;"
                                           placeholder="需带http协议, 如: http://www.baidu.com">
                                </td>
                            </tr>
                            <tr>
                                <th width="15%">链接规则:</th>
                                <td>
                                <textarea name="slink_rules" id="spider_source"
                                          class="form-control resizable processed"
                                          rows="10" style="width: 100%;"
                                          title="编辑链接规则"
                                          placeholder="链接规则,一行代表一个规则..支持标签
<随机字符> 随机字符串
<随机数字> 随机纯数字 09221
例如:
/hot<随机字符>/
/hot<随机字符>.html">
/hot<随机字符>/
/hot<随机字符>.html
/app<随机字符>/
/app<随机字符>.html
</textarea>
                                </td>
                            </tr>
                            <tr>
                                <th width="15%">优先级:</th>
                                <td>
                                    <select name="slink_level" title="功能未实现. 选择链接等级..."
                                            style="width: 100%;">
                                        <option value="0">低</option>
                                        <option value="1">中</option>
                                        <option value="2">高</option>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <th></th>
                                <td>
                                    <input class="btn btn-success" type="submit" value="添加">
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- 添加站点结束 -->
    <!-- 编辑站点开始 -->
    <div class="modal fade" id="View-Sites" tabindex="-1" role="dialog" aria-labelledby="ViewSites" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times;</button>
                    <h4 class="modal-title" id="ViewSites">查看轮链</h4>
                </div>
                <div class="modal-body">
                    <table class="table table-striped table-bordered table-hover table-condensed">
                        <tr>
                            <th width="15%">提示:</th>
                            <td><span class="label label-warning" style="width: 100%;">编辑后及时生效.</span>
                            </td>
                        </tr>
                        <tr>
                            <th width="15%">网站地址:</th>
                            <td>
                                <input class="input-medium" type="text" name="view_url" style="width: 100%;"
                                       placeholder="填写网站地址 如: http://www.baidu.com" readonly>
                            </td>
                        </tr>
                        <tr>
                            <th width="15%">优先级:</th>
                            <td>
                                <select name="edit_slink_level" title="未实现功能. 选择链接等级..."
                                        style="width: 100%;">
                                    <option value="0">低</option>
                                    <option value="1">中</option>
                                    <option value="2">高</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th width="15%">链接规则:</th>
                            <td>
                            <textarea name="edit_slink_rules" id="spider_source"
                                      class="form-control resizable processed"
                                      rows="10" style="width: 100%;"
                                      title="编辑链接规则"
                                      placeholder="链接规则,一行代表一个规则..支持标签
<随机字符> 随机字符串
<随机数字> 随机纯数字 09221
例如:
/hot<随机字符>/
/hot<随机字符>.html">
/hot<随机字符>/
/hot<随机字符>.html
/app<随机字符>/
/app<随机字符>.html
</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th></th>
                            <td><input class="btn btn-success" id="edit_sites" type="button" value="保存"></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- 编辑站点结束 -->

{% endblock %}

{% block name %}pool_link{% endblock %}
{% block load_js %}
    {{ super() }}
    <script>
        // 编辑网站
        $("a[name='ViewSite']").click(function () {
            // 获取当前点击的列表ID
            site_sid = $(this).attr('data-site-sid');
            view_url = $("input[name='view_url']");
            view_slink_level = $("select[name='edit_slink_level']");
            view_slink_rules = $("textarea[name='edit_slink_rules']");

            $.post("{{ url_for('link.find_pool_link') }}", {sid: site_sid}, function (data, textStatus, xhr) {
                // 请求成功
                if (data.status === true) {
                    view_url.val(data.data._id);
                    view_slink_level.val(data.data.hit);
                    view_slink_rules.val(data.data.rules.join("\r\n"));
                    $("#View-Sites").modal('show');
                }
            });
        });

        // 编辑事件
        $("#edit_sites").click(function () {
            if (confirm("是否修改轮链配置?")) {
                console.log(view_slink_level.val());
                console.log(view_slink_rules.val());
                update_data = {
                    sid: site_sid,
                    slink_level: view_slink_level.val(),
                    slink_rules: view_slink_rules.val(),
                }

                for (var i in update_data) {
                    if (update_data[i] === "") {
                        alert("请填写完整信息后在修改!");
                        return false;
                    }
                }

                $.post("{{ url_for('link.edit_pool_link') }}", update_data, function (data, textStatus, xhr) {
                    if (data.status == true) {
                        alert(data.info);
                        window.location.reload();
                    }

                    if (data.status == false) {
                        alert(data.info);
                        return false;
                    }
                });
            }
        });

        // 添加菜单
        function add() {
            $("input[name='title']").val('');
            $('#bjy-add').modal('show');
        }

        // 删除网站监听事件
        $("a[name='DeleteSite']").click(function (event) {
            xsid = $(this).attr('data-site-sid');
            if (confirm("你是否真的要删除ID为【" + xsid + "】的网站轮链配置文件\n如果删除将不能恢复，你确定继续吗？")) {
                $.post("{{ url_for('link.del_pool_link') }}", {sid: xsid}, function (data, textStatus, xhr) {
                    if (data.status == true) {
                        alert(":( 删除成功，请等待控制端删除...!");
                        window.location.reload();
                    } else {
                        alert(":) 删除失败，可能是人品问题~");
                        window.location.reload();
                    }
                });
            }
        });

    </script>
{% endblock %}

templates/show_spider.html
{% extends "nav.html" %}
{% block title %}蜘蛛爬行统计{% endblock %}
{% block content %}
<div class="page-header">
    <h1> 首页&gt; 
        {% if request.args.getlist('show')[0] == 'today' %}
        今天
        {% else %}
        昨天
        {% endif %}

        {% if request.args.getlist('spider')[0] == 'all_spider' %}
        全部
        {% elif request.args.getlist('spider')[0] == 'baidu_spider' %}
        百度
        {% elif request.args.getlist('spider')[0] == 'sogou_spider' %}
        搜狗
        {% elif request.args.getlist('spider')[0] == '360_spider' %}
        360
        {% elif request.args.getlist('spider')[0] == 'bing_spider' %}
        必应
        {% elif request.args.getlist('spider')[0] == 'google_spider' %}
        谷歌
        {% elif request.args.getlist('spider')[0] == 'sm_spider' %}
        神马
        {% endif %}
        蜘蛛爬行统计</h1>
</div>
<div class="col-xs-12">
    <ul class="nav nav-tabs padding-12 tab-color-blue background-blue">
        {% if request.args.getlist('spider')[0] == 'all_spider' %}<li id="all_list" class="active">{% else %}<li id="all_list">{% endif %}

        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='all_spider') }}">全部蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='all_spider') }}">全部蜘蛛</a>
        {% endif %}
        </li>

        {% if request.args.getlist('spider')[0] == 'baidu_spider' %}<li id="baiduspider" class="active">{% else %}<li id="baiduspider">{% endif %}
        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='baidu_spider') }}">百度蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='baidu_spider') }}">百度蜘蛛</a>
        {% endif %}
        </li>

        {% if request.args.getlist('spider')[0] == 'sogou_spider' %}<li id="sogouspider" class="active">{% else %}<li id="sogouspider">{% endif %}
        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='sogou_spider') }}">搜狗蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='sogou_spider') }}">搜狗蜘蛛</a>
        {% endif %}
        </li>

        {% if request.args.getlist('spider')[0] == '360_spider' %}<li id="sogouspider" class="active">{% else %}<li id="sogouspider">{% endif %}
        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='360_spider') }}">360蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='360_spider') }}">360蜘蛛</a>
        {% endif %}
        </li>

        {% if request.args.getlist('spider')[0] == 'bing_spider' %}<li id="bingspider" class="active">{% else %}<li id="bingspider">{% endif %}
        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='bing_spider') }}">必应蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='bing_spider') }}">必应蜘蛛</a>
        {% endif %}
        </li>
        
        {% if request.args.getlist('spider')[0] == 'google_spider' %}<li id="googlespider" class="active">{% else %}<li id="googlespider">{% endif %}
        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='google_spider') }}">谷歌蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='google_spider') }}">谷歌蜘蛛</a>
        {% endif %}
        </li>

        {% if request.args.getlist('spider')[0] == 'sm_spider' %}<li id="smspider" class="active">{% else %}<li id="smspider">{% endif %}
        {% if request.args.getlist('show')[0] == 'today' %}
            <a href="{{ url_for('show_spider', show='today', spider='sm_spider') }}">神马蜘蛛</a>
        {% else %}
            <a href="{{ url_for('show_spider', show='yesterday', spider='sm_spider') }}">神马蜘蛛</a>
        {% endif %}
        </li>

    </ul>
    <div class="tabbable">
        <div class="tab-content">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>爬行ID</th>
                    <th>爬行URI</th>
                    <th>蜘蛛名</th>
                    <th>爬行 User-Agent</th>
                    <th>爬行时间</th>
                </tr>
                {% for d in data %}
                <tr>
                    <td>{{ d._id }}</td>
                    <td><a href="javascript:;" name="domain">{{ d.url }}</a></td>
                    <td><b class="red">{{ d.name }}</b></td>
                    <td><b class="blue">{{ d.user_agent }}</b></td>
                    <td><b class="red">{{ d.create_time }}</b></td>
                </tr>
                {% endfor %}
                
            </table>
            <nav style="text-align: center">
                <ul class="pagination">
                    <li><a class="start" href="{{ url_for('show_spider', page='1', spider=request.args.get('spider', '')) }}">首页</a></li>
                    {% for p in page %}
                        {% if current_page == p %}
                            <li class="active">
                                <a class="num" href="{{ url_for('show_spider', page=current_page, spider=request.args.get('spider', '')) }}">{{ p }}</a>
                            </li>
                        {% else %}
                            <li><a class="num" href="{{ url_for('show_spider', page=p, spider=request.args.get('spider', '')) }}">{{ p }}</a></li>
                        {% endif %}
                    {% endfor %}
                    <li><a class="end" href="{{ url_for('show_spider', page=max_page, spider=request.args.get('spider', '')) }}">尾页</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

{% block name%}spider{%endblock%}